### ISSUE TITLE
Tracking issue for Client Metrics

### ISSUE THREAD

**Issue by DevBlocky** [DevBlocky/scalpel#9]
My plan was to use VictoriaMetrics because of the ease of use of `vmrange`s that directly replace buckets of traditional prometheus metrics, however there is no VictoriaMetrics implementation in Rust unfortunately. In the future, a modified library might be used as a Victoria Metrics library but my plan right now is to use the rust Prometheus impl.

## Generic Layout
- A new metrics structure will be created in a separate file that will contain all metrics and the registry.
- This metrics structure will be added to the Global State.
- All parts of the program that have access to the Global State will directly update the metrics that they need to.

**Comment by DevBlocky** [comment]
Additional idea:

Buckets should be configurable by the end user using the configuration file, however a default setting should be available if they don't want to configure it themselves.

**Comment by DevBlocky** [comment]
Definite Application metrics to track:

- [x] Request Process Durations (label HIT/MISS)
- [x] Total Client Requests (label HIT/MISS)
- [x] Total Bytes Served
- [x] Total Bytes Downloaded from Upstream
- [x] Cache Load Durations
- [x] Cache Save Durations
- [x] Total Cache Size

Maybe Application metrics to track:

- [x] Dropped Requests (Invalid Token, Invalid Parameters, etc.)
- [ ] Upstream Download Durations
- [ ] Total Browser Already Cached
